version: '3.8'

services:

  apache:
    image: php:8.3-apache
    container_name: apache
    command: >
      bash -c "apt-get update && apt-get install -y libicu-dev libjpeg-dev libpng-dev libwebp-dev libfreetype6-dev && docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype && docker-php-ext-install intl pdo_mysql gd && a2enmod rewrite headers deflate expires && apache2-foreground"
    ports:
      - "8080:80"
    volumes:
      - ./localhost/html/ivy:/var/www
      - ./localhost/sites-available:/etc/apache2/sites-available
      - ./localhost/sites-enabled:/etc/apache2/sites-enabled
      - ./localhost/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - /usr/local/bin/node:/usr/local/bin/node
      - /usr/local/bin/npm:/usr/local/bin/npm
      - /usr/local/bin/npx:/usr/local/bin/npx

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./localhost/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  mailcatcher:
    image: dockage/mailcatcher
    container_name: mailcatcher
    hostname: mailcatcher.local
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP
