version: '3.8'

services:

  apache:
    image: docker.io/php:8.4-apache-bullseye
    container_name: ${APACHE_HOST:-ivy_apache}
    command: >
      bash -c "apt-get update && apt-get install -y \
        libicu-dev libjpeg-dev libpng-dev libwebp-dev libfreetype6-dev curl \
        && curl -sL https://deb.nodesource.com/setup_current.x | bash - \
        && apt-get install -y nodejs \
        && docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype \
        && docker-php-ext-install intl pdo_mysql gd \
        && a2enmod rewrite headers deflate expires \
        && apache2-foreground"
    ports:
      - "${SERVER_PORT:-8080}:80"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/public
    volumes:
      - ../:/var/www
      - ./sites-available:/etc/apache2/sites-available
      - ./sites-enabled:/etc/apache2/sites-enabled
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini

  mysql:
    image: docker.io/mysql
    container_name: ${DB_HOST:-ivy_mysql}
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE:-ivy_db}
      MYSQL_USER: ${DB_USERNAME:-ivy_db_username}
      MYSQL_PASSWORD: ${DB_PASSWORD:-ivy_db_password}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - ./mysql/ivy.sql:/docker-entrypoint-initdb.d/ivy.sql

  mailcatcher:
    image: docker.io/dockage/mailcatcher
    container_name: ${MAIL_HOST:-ivy_mailcatcher}
    hostname: ${MAIL_HOST:-ivy_mailcatcher}
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP
